/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CitySelector: typeof import('./src/components/CitySelector.vue')['default']
    ForecastTable: typeof import('./src/components/ForecastTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SurfAdviceTooltip: typeof import('./src/components/SurfAdviceTooltip.vue')['default']
  }
}
